on:
  workflow_call:
    inputs:
      build-tool:
        type: string
        default: uv
      build-tool-version:
        type: string
        required: false
      python-version:
        type: string
        default: '3.14'
    outputs:
      version:
        value: ${{ jobs.version.outputs.version }}

permissions:
  contents: read

jobs:
  version:
    runs-on: ubuntu-26.04
    env:
      # renovate: datasource=pypi depName=uv versioning=semver-coerced
      UV_VERSION: 0.12.23
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - if: inputs.build-tool != 'uv'
        run: |
          echo "The only supported build tool is uv."
          exit 1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ inputs.python-version }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          cache-suffix: actions-releases
          version: ${{ inputs.build-tool-version || env.UV_VERSION }}
      - run: uv sync
      - id: version
        run: |
          version=$(uv run cz version --project)
          echo "version=$version" >> "$GITHUB_OUTPUT"
